version: "3.8"

services:
    #Container MYSQL
    db:
        image: mysql
        container_name: docker_mysql
        restart: always
        volumes: 
            - db-data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER_NAME}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD}
        networks: 
            - dev

    #Container PHPMYADMIN
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        container_name: docker_phpmyadmin
        restart: always
        environment:
            PMA_HOST: ${PMA_HOST}
        ports:
            - "${PMA_PORT}:80"
        networks:
            - dev
            
    #APACHE + PHP 7.4 ON FOLDER PHP
    www:
        build: php
        container_name: docker_www
        ports:
            - ${HTTP_PORT}:80
        volumes: 
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev
            
networks: 
    dev:

volumes: 
    db-data: